version: "3"
services:
  greenbay_api:
    build: .
    ports:
      - "80:8000"
    env_file:
      - .env

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=greenbay_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=toor
    depends_on:
      - greenbay_api
    container_name: mongodb
    ports:
      - "2717:27017"
    volumes:
      - data:/data/db

volumes:
  data:


