version: "3.8"
services:
  mongodb:
    container_name: mongodb
    image: mongo:4.4.6
    restart: always
    expose:
      - 27017
    ports:
      - "27017:27017"
    environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
        - mongo_data:/data/db
        - mongo_config:/data/configdb
    networks:
        - green_bay


  green_bay_api:
    container_name: green_bay_api
    build: .
    restart: on-failure
    expose:
      - 8001
    ports:
      - "80:8001"
    env_file:
      - .env
    networks:
      - green_bay

  mongo_express:
    container_name: mongo_express_gb
    image: mongo-express
    restart: on-failure
    depends_on: [ mongodb ]
    environment:
#      ME_CONFIG_MONGODB_SERVER: mongodb
#      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
#      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
#      ME_CONFIG_BASICAUTH_USERNAME: root
#      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
    expose:
      - 5001
    ports:
      - "5001:8081"
    networks:
      - green_bay
    volumes:
      - ./mongo_express/config.js:/mongo_express/config.js

volumes:
  mongo_data:
  mongo_config:
  mongo_express:

networks:
  default:
    name: green_bay
  green_bay:
    driver: bridge
