version: "3"
services:

  mongo-db:
    container_name: mongo-db
    image: mongo:latest
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=toor
      - MONGO_INITDB_DATABASE=root_db
      - MONGO_INITDB_USERNAME=admin
      - MONGO_INITDB_PASSWORD=admin123
    expose:
      - 9000
    ports:
      - "9000:27017"
    networks:
      - network
    volumes:
      - mongo-data:/data/db:rw
      - mongo-config:/data/configdb:rw


  greenbay_api:
    container_name: greenbay_api
    build: .
    restart: on-failure
    depends_on:
      mongo-db:
        condition: service_started
    expose:
      - 80
    ports:
      - "80:8000"
    env_file:
      - .env
    links:
      - mongo-db:mongo-db
    networks:
      - network

  mongo-express:
    image: mongo-express
    restart: on-failure
    depends_on:
      mongo-db:
        condition: service_started
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-db
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=toor
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    expose:
      - 5001
    ports:
      - "5001:8081"
    networks:
      - network
    links:
      - mongo-db:mongo-db

volumes:
  mongo-data:
  mongo-config:

networks:
  network:
    driver: bridge




