version: "3.8"
services:
  green_bay_api:
    container_name: green_bay_api
    build: .
    restart: on-failure
    expose:
      - 8001
    ports:
      - "80:8001"
    env_file:
      - .env
    networks:
      - green_bay


#  mongo_express:
#    image: mongo-express
#    restart: on-failure
#    environment:
#      - ME_CONFIG_MONGODB_SERVER=mongodb+srv://app1.bqmqa.mongodb.net/greenbay_db?retryWrites=true&w=majority
#      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=skunk
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=g0BJX2hfxH3W6T3q
#      - ME_CONFIG_BASICAUTH_USERNAME=skunk
#      - ME_CONFIG_BASICAUTH_PASSWORD=g0BJX2hfxH3W6T3q
#    expose:
#      - 5001
#    ports:
#      - "5001:8081"
#    networks:
#      - green_bay

volumes:
  mongo-data:
  mongo-config:

networks:
  green_bay:
    driver: bridge







