version: "3"
services:
  mongodb:
    image: mongo:5
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=greenbay_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=toor
    ports:
      - "2717:27017"
    volumes:
      - data:/data/db

  greenbay_api:
    container_name: greenbay_api
    build: .
    restart: always
    depends_on:
      mongodb:
        condition: service_started
    links:
      - mongodb
    ports:
      - "80:8000"
    env_file:
      - .env

  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    depends_on:
        mongodb:
          condition: service_started
    ports:
      - "5001:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=toor
      - ME_CONFIG_MONGODB_URL=mongodb://root@toor@localhost:2717

volumes:
  data:


